export const FETCH_TASK_LISTS = "FETCH_TASK_LISTS";
export const FETCH_TASK_LIST = "FETCH_TASK_LIST";
export const FETCH_TASKS = "FETCH_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_CURRENT_TASK_LIST = "UPDATE_CURRENT_TASK_LIST";
export const CREATE_TASK_LIST = "CREATE_TASK_LIST";
export const LOGIN = "LOGIN";
