export const FETCH_TASK_LISTS = "FETCH_TASK_LISTS";
export const FETCH_TASK_LIST = "FETCH_TASK_LIST";
export const UPDATE_CURRENT_TASK_LIST = "UPDATE_CURRENT_TASK_LIST";
export const CREATE_TASK_LIST = "CREATE_TASK_LIST";
